-- ═══ GLAM Metadata Seed SQL for Production ═══
-- Run in DBeaver. Vocab IDs 1-4 already exist.
-- ID 5 is custom 'Kandaga Book Vocabulary'.
-- New vocabularies start at ID 6 (seed VRA=5 +1).

-- ═══ Vocabularies (24 new, production IDs 6-29) ═══
INSERT INTO metadata_vocabularies
  (id, namespace_url, prefix, label, information, inserted_at, updated_at)
VALUES
  (6, 'http://www.vraweb.org/vracore/vracore4#', 'vra', 'VRA Core 4.0', 'Visual Resources Association Core Categories — three-entity model (Work, Image, Collection) for visual art resources. Library of Congress.', NOW(), NOW()),
  (7, 'http://www.getty.edu/CDWA/CDWALite/', 'cdwalite', 'CDWA Lite', 'Categories for the Description of Works of Art (Lite subset) — OAI-PMH XML schema for art objects. Getty Research Institute.', NOW(), NOW()),
  (8, 'http://www.w3.org/2003/12/exif/ns#', 'exif', 'EXIF', 'Exchangeable Image File Format — technical metadata embedded in image files (ISO 12234-2).', NOW(), NOW()),
  (9, 'http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/', 'iptc', 'IPTC Photo Metadata', 'IPTC Core — descriptive and rights metadata for photographic images. International Press Telecommunications Council.', NOW(), NOW()),
  (10, 'http://ns.adobe.com/xap/1.0/', 'xmp', 'XMP', 'Adobe Extensible Metadata Platform — extensible metadata embedded in digital files. Includes xmpRights and xmpMM sub-namespaces.', NOW(), NOW()),
  (11, 'https://schema.org/', 'schema', 'Schema.org', 'Schema.org vocabulary — structured data for web discoverability (JSON-LD / Microdata). Covers CreativeWork, VisualArtwork, Book, ArchiveComponent, Museum, etc.', NOW(), NOW()),
  (12, 'http://www.loc.gov/MARC21/slim#', 'marc21', 'MARC 21', 'Machine-Readable Cataloging — primary library catalogue interchange format. Library of Congress.', NOW(), NOW()),
  (13, 'http://www.loc.gov/mods/v3#', 'mods', 'MODS 3.x', 'Metadata Object Description Schema — XML-based, MARC-derived library metadata. Widely used in institutional repositories. Library of Congress.', NOW(), NOW()),
  (14, 'http://id.loc.gov/ontologies/bibframe/', 'bf', 'BIBFRAME 2.0', 'Bibliographic Framework — RDF/Linked Data replacement for MARC modelling Work → Instance → Item. Library of Congress.', NOW(), NOW()),
  (15, 'http://www.loc.gov/METS/', 'mets', 'METS', 'Metadata Encoding and Transmission Standard — XML container for packaging digital objects with descriptive, administrative and structural metadata. Library of Congress.', NOW(), NOW()),
  (16, 'http://ns.editeur.org/onix/3.0/reference#', 'onix', 'ONIX 3.0', 'Online Information eXchange — book supply-chain metadata standard. EDItEUR. Useful for acquisition and e-resource workflows.', NOW(), NOW()),
  (17, 'http://www.archiveshub.ac.uk/isadg/', 'isadg', 'ISAD(G)', 'General International Standard Archival Description (2nd ed.) — hierarchical description Fonds → Series → File → Item. International Council on Archives.', NOW(), NOW()),
  (18, 'http://ead3.archivists.org/schema/#', 'ead', 'EAD 3', 'Encoded Archival Description — XML finding aid standard implementing ISAD(G). Society of American Archivists / Library of Congress.', NOW(), NOW()),
  (19, 'http://www.archivists.org/ns/eac-cpf#', 'eaccpf', 'EAC-CPF 2.0', 'Encoded Archival Context — Corporate bodies, Persons, Families. Authority records for archival agents. ICA / SAA.', NOW(), NOW()),
  (20, 'https://www.ica.org/standards/RiC/ontology#', 'ric', 'Records in Contexts (RiC)', 'Next-generation archival description standard — OWL Linked Data ontology superseding ISAD(G), ISAAR(CPF), ISDF, ISDIAH. ICA 2023.', NOW(), NOW()),
  (21, 'http://www.loc.gov/premis/rdf/v3/', 'premis', 'PREMIS 3.0', 'PREservation Metadata: Implementation Strategies — standard for digital preservation metadata (objects, events, agents, rights). Library of Congress.', NOW(), NOW()),
  (22, 'http://www.archiveshub.ac.uk/isaar/', 'isaar', 'ISAAR(CPF)', 'International Standard Archival Authority Record for Corporate bodies, Persons, Families (2nd ed.). ICA. Still widely used in AtoM software.', NOW(), NOW()),
  (23, 'http://www.cidoc-crm.org/cidoc-crm/', 'crm', 'CIDOC CRM', 'Conceptual Reference Model for Cultural Heritage Documentation (ISO 21127) — semantic backbone for CH Linked Data. ICOM-CIDOC.', NOW(), NOW()),
  (24, 'http://www.collectionstrust.org.uk/spectrum/', 'spectrum', 'SPECTRUM 5.1', 'UK Museum Collections Management Standard — 21 collection management procedures and object information groups. Collections Trust.', NOW(), NOW()),
  (25, 'http://www.lido-schema.org/schema/v1.0/lido-v1.0#', 'lido', 'LIDO 1.1', 'Lightweight Information Describing Objects — XML interchange format for museum objects used by Europeana and national CH aggregators. ICOM-CIDOC.', NOW(), NOW()),
  (26, 'https://www.object-id.com/vocab/', 'objectid', 'ICOM Object ID', 'Standard for documenting cultural objects to prevent theft and aid recovery. 9 minimum categories. ICOM / Interpol.', NOW(), NOW()),
  (27, 'http://www.europeana.eu/schemas/edm/', 'edm', 'Europeana Data Model (EDM)', 'Europeana Data Model — aggregation model for CH portals, wrapping DC and CIDOC CRM into Linked Data. Europeana Foundation.', NOW(), NOW()),
  (28, 'http://www.w3.org/2004/02/skos/core#', 'skos', 'SKOS', 'Simple Knowledge Organization System — W3C standard for controlled vocabularies, thesauri and classification schemes (AAT, LCSH, TGN).', NOW(), NOW()),
  (29, 'http://iiif.io/api/presentation/3#', 'iiif', 'IIIF Presentation API 3', 'International Image Interoperability Framework Presentation API — Manifest model for image delivery and viewer interoperability across GLAM.', NOW(), NOW());

-- ═══ Properties (vocabulary_id = seed + 1) ═══
INSERT INTO metadata_properties
  (vocabulary_id, local_name, label, information, type_value, owner_id, inserted_at, updated_at)
VALUES
  (6, 'agent', 'Agent', 'Individuals or groups responsible for the creation, production, or alteration of a work or image.', 'text', NULL, NOW(), NOW()),
  (6, 'culturalContext', 'Cultural Context', 'The name of the culture, people, or nationality from which the work originated.', 'text', NULL, NOW(), NOW()),
  (6, 'date', 'Date', 'Date or range of dates associated with the creation, alteration, or discovery of the work.', 'date', NULL, NOW(), NOW()),
  (6, 'description', 'Description', 'A free-text description of the work, image, or collection.', 'textarea', NULL, NOW(), NOW()),
  (6, 'inscription', 'Inscription', 'All marks or written words added to the surface of the work at the time of production or later.', 'textarea', NULL, NOW(), NOW()),
  (6, 'location', 'Location', 'The geographic location and/or name of the repository, site, or event associated with the work.', 'text', NULL, NOW(), NOW()),
  (6, 'material', 'Material', 'The substance of which the work is composed.', 'text', NULL, NOW(), NOW()),
  (6, 'measurements', 'Measurements', 'The physical dimensions, size, scale, or format of the work.', 'text', NULL, NOW(), NOW()),
  (6, 'relation', 'Relation', 'Reference to another Work, Image, or Collection that has a relationship to the described resource.', 'text', NULL, NOW(), NOW()),
  (6, 'rights', 'Rights', 'Information about the rights management associated with the work.', 'textarea', NULL, NOW(), NOW()),
  (6, 'source', 'Source', 'A reference to the source of the information recorded about the work.', 'text', NULL, NOW(), NOW()),
  (6, 'stateEdition', 'State / Edition', 'The state or edition of the work.', 'text', NULL, NOW(), NOW()),
  (6, 'stylePeriod', 'Style / Period', 'A defined style, historical period, group, school, dynasty, movement, etc. whose characteristics are represented in the work.', 'text', NULL, NOW(), NOW()),
  (6, 'subject', 'Subject', 'Terms or phrases that describe, identify, or interpret the work and what it depicts or expresses.', 'text', NULL, NOW(), NOW()),
  (6, 'technique', 'Technique', 'The processes, methods, and means by which the work was created.', 'text', NULL, NOW(), NOW()),
  (6, 'textref', 'Text Reference', 'The name and location within a text of a citation or reference relating to the work.', 'text', NULL, NOW(), NOW()),
  (6, 'title', 'Title', 'The title or identifying phrase given to a work.', 'text', NULL, NOW(), NOW()),
  (6, 'worktype', 'Work Type', 'The specific kind of object or work being described (e.g., painting, photograph, sculpture).', 'text', NULL, NOW(), NOW()),
  (7, 'objectWorkType', 'Object / Work Type', 'The specific kind of object or work being catalogued.', 'text', NULL, NOW(), NOW()),
  (7, 'titles', 'Titles', 'Names, titles, or identifying phrases given to the work.', 'text', NULL, NOW(), NOW()),
  (7, 'creatorDescription', 'Creator Description', 'Describes the maker(s) of the work.', 'text', NULL, NOW(), NOW()),
  (7, 'creationDate', 'Creation Date', 'The date or date range when the work was created.', 'date', NULL, NOW(), NOW()),
  (7, 'stylesCultures', 'Styles / Cultures', 'The style, period, group, or culture to which the work belongs.', 'text', NULL, NOW(), NOW()),
  (7, 'currentLocation', 'Current Location', 'The current location (repository, museum, site) where the work is held.', 'text', NULL, NOW(), NOW()),
  (7, 'subjectMatter', 'Subject Matter', 'What is depicted or expressed in the work.', 'textarea', NULL, NOW(), NOW()),
  (7, 'classificationTerm', 'Classification Term', 'The term used to classify or categorise the work.', 'text', NULL, NOW(), NOW()),
  (7, 'materialsTechniques', 'Materials & Techniques', 'The materials and techniques used in making the work.', 'text', NULL, NOW(), NOW()),
  (7, 'measurements', 'Measurements', 'The dimensions, size, scale, or format of the work.', 'text', NULL, NOW(), NOW()),
  (7, 'inscriptions', 'Inscriptions', 'Marks or written words on the work.', 'textarea', NULL, NOW(), NOW()),
  (7, 'stateEditionDescription', 'State / Edition Description', 'The specific state, edition, or version of the work.', 'text', NULL, NOW(), NOW()),
  (7, 'descriptiveNotes', 'Descriptive Notes', 'Free-text notes about the work.', 'textarea', NULL, NOW(), NOW()),
  (7, 'associatedNames', 'Associated Names', 'Names of persons or corporate bodies associated with the work (other than creators).', 'text', NULL, NOW(), NOW()),
  (7, 'relatedWorks', 'Related Works', 'Works related to the described work.', 'text', NULL, NOW(), NOW()),
  (7, 'rightsAndReproduction', 'Rights & Reproduction', 'Information about copyright and reproduction rights.', 'textarea', NULL, NOW(), NOW()),
  (7, 'recordID', 'Record ID', 'A unique identifier for the catalogue record.', 'text', NULL, NOW(), NOW()),
  (8, 'imageWidth', 'Image Width', 'The number of columns of image data (pixels per row).', 'integer', NULL, NOW(), NOW()),
  (8, 'imageLength', 'Image Length', 'The number of rows of image data.', 'integer', NULL, NOW(), NOW()),
  (8, 'bitsPerSample', 'Bits Per Sample', 'The number of bits per image component.', 'integer', NULL, NOW(), NOW()),
  (8, 'colorSpace', 'Color Space', 'The colour space information tag (e.g., sRGB, Adobe RGB).', 'text', NULL, NOW(), NOW()),
  (8, 'dateTimeOriginal', 'Date Time Original', 'Date and time when the original image data was generated.', 'date', NULL, NOW(), NOW()),
  (8, 'make', 'Camera Make', 'The manufacturer of the recording equipment.', 'text', NULL, NOW(), NOW()),
  (8, 'model', 'Camera Model', 'The model name or model number of the equipment.', 'text', NULL, NOW(), NOW()),
  (8, 'exposureTime', 'Exposure Time', 'Exposure time, in seconds.', 'text', NULL, NOW(), NOW()),
  (8, 'fNumber', 'F-Number', 'The F number (aperture) at the time of capture.', 'text', NULL, NOW(), NOW()),
  (8, 'isoSpeedRatings', 'ISO Speed Ratings', 'The ISO speed and ISO latitude of the camera.', 'integer', NULL, NOW(), NOW()),
  (8, 'gpsInfo', 'GPS Info', 'GPS measurement info including latitude, longitude, and altitude.', 'text', NULL, NOW(), NOW()),
  (9, 'headline', 'Headline', 'A brief publishable synopsis or summary of the contents of the photograph.', 'text', NULL, NOW(), NOW()),
  (9, 'caption', 'Caption / Abstract', 'A textual description, including captions, of the image.', 'textarea', NULL, NOW(), NOW()),
  (9, 'creator', 'Creator', 'The creator or photographer of the image.', 'text', NULL, NOW(), NOW()),
  (9, 'jobTitle', 'Creator''s Job Title', 'The job title of the creator.', 'text', NULL, NOW(), NOW()),
  (9, 'keywords', 'Keywords', 'Keywords to express the subject of the image.', 'text', NULL, NOW(), NOW()),
  (9, 'subjectCode', 'Subject Code', 'Structured subjects (IPTC Subject NewsCode).', 'text', NULL, NOW(), NOW()),
  (9, 'copyrightNotice', 'Copyright Notice', 'The copyright notice for claiming the intellectual property.', 'text', NULL, NOW(), NOW()),
  (9, 'creditLine', 'Credit Line', 'The credit to person(s) and/or organisation(s) required by the supplier.', 'text', NULL, NOW(), NOW()),
  (9, 'dateCreated', 'Date Created', 'Designates the date and optionally the time the intellectual content was created.', 'date', NULL, NOW(), NOW()),
  (9, 'city', 'City', 'Name of the city of the location shown in the image.', 'text', NULL, NOW(), NOW()),
  (9, 'countryName', 'Country Name', 'The name of the country shown in the image.', 'text', NULL, NOW(), NOW()),
  (10, 'CreateDate', 'Create Date', 'The date and time the resource was created.', 'date', NULL, NOW(), NOW()),
  (10, 'ModifyDate', 'Modify Date', 'The date and time the resource was last modified.', 'date', NULL, NOW(), NOW()),
  (10, 'Rating', 'Rating', 'A user-assigned rating for the file (–1 to 5 stars).', 'integer', NULL, NOW(), NOW()),
  (10, 'UsageTerms', 'Usage Terms', 'A collection of text instructions on how a resource can be legally used.', 'textarea', NULL, NOW(), NOW()),
  (10, 'DocumentID', 'Document ID', 'The common identifier for all versions and renditions of a document.', 'text', NULL, NOW(), NOW()),
  (10, 'InstanceID', 'Instance ID', 'An identifier for a specific incarnation of a document, updated each time the file is saved.', 'text', NULL, NOW(), NOW()),
  (11, 'name', 'Name', 'The name of the item.', 'text', NULL, NOW(), NOW()),
  (11, 'description', 'Description', 'A description of the item.', 'textarea', NULL, NOW(), NOW()),
  (11, 'url', 'URL', 'URL of the item.', 'uri', NULL, NOW(), NOW()),
  (11, 'dateCreated', 'Date Created', 'The date on which the CreativeWork was created.', 'date', NULL, NOW(), NOW()),
  (11, 'dateModified', 'Date Modified', 'The date on which the CreativeWork was most recently modified.', 'date', NULL, NOW(), NOW()),
  (11, 'creator', 'Creator', 'The creator/author of this content or rating.', 'text', NULL, NOW(), NOW()),
  (11, 'license', 'License', 'A license document that applies to this content.', 'uri', NULL, NOW(), NOW()),
  (11, 'artEdition', 'Art Edition', 'The number of copies when multiple copies of a piece of artwork are produced — e.g. for a limited edition of 20 prints.', 'integer', NULL, NOW(), NOW()),
  (11, 'artMedium', 'Art Medium', 'The material used (e.g. Oil, Watercolour, Acrylic, Linocut, Marble, Cyanotype, Digital, Lithograph).', 'text', NULL, NOW(), NOW()),
  (11, 'artform', 'Artform', 'An established vocabulary of artforms (e.g., Painting, Drawing, Sculpture, Print, Film, Installation).', 'text', NULL, NOW(), NOW()),
  (11, 'artworkSurface', 'Artwork Surface', 'The supporting materials for the artwork (e.g. Canvas, Panel, Paper, Wood, Board).', 'text', NULL, NOW(), NOW()),
  (11, 'depth', 'Depth', 'The depth of the item.', 'text', NULL, NOW(), NOW()),
  (11, 'height', 'Height', 'The height of the item.', 'text', NULL, NOW(), NOW()),
  (11, 'width', 'Width', 'The width of the item.', 'text', NULL, NOW(), NOW()),
  (11, 'locationCreated', 'Location Created', 'The location where the artwork was created.', 'text', NULL, NOW(), NOW()),
  (11, 'encodingFormat', 'Encoding Format', 'MIME format (or media type) of the content.', 'text', NULL, NOW(), NOW()),
  (12, 'controlNumber', 'Control Number (001)', 'Unique control number assigned by the organisation whose system number appears in field 003.', 'text', NULL, NOW(), NOW()),
  (12, 'controlNumberIdentifier', 'Control Number Identifier (003)', 'MARC code for the organisation whose system control number is contained in field 001.', 'text', NULL, NOW(), NOW()),
  (12, 'latestTransactionDateTime', 'Latest Transaction Date/Time (005)', 'Date and time of the latest record transaction.', 'date', NULL, NOW(), NOW()),
  (12, 'fixedLengthDataElements', 'Fixed-Length Data Elements (008)', 'Positionally-defined data elements for all types of material.', 'text', NULL, NOW(), NOW()),
  (12, 'isbn', 'ISBN (020)', 'The International Standard Book Number.', 'text', NULL, NOW(), NOW()),
  (12, 'issn', 'ISSN (022)', 'The International Standard Serial Number.', 'text', NULL, NOW(), NOW()),
  (12, 'catalogingSource', 'Cataloging Source (040)', 'MARC code for the organisation that created, transcribed, or modified the record.', 'text', NULL, NOW(), NOW()),
  (12, 'languageCode', 'Language Code (041)', 'Language code(s) for the language of the item.', 'text', NULL, NOW(), NOW()),
  (12, 'lcCallNumber', 'LC Call Number (050)', 'Library of Congress call number.', 'text', NULL, NOW(), NOW()),
  (12, 'deweyDecimal', 'Dewey Decimal Classification (082)', 'Dewey Decimal Classification number.', 'text', NULL, NOW(), NOW()),
  (12, 'personalName', 'Personal Name — Main Entry (100)', 'Personal name as the main entry (primary access point) for the record.', 'text', NULL, NOW(), NOW()),
  (12, 'corporateName', 'Corporate Name — Main Entry (110)', 'Corporate name as the main entry for the record.', 'text', NULL, NOW(), NOW()),
  (12, 'uniformTitle', 'Uniform Title (130/240)', 'A distinctive title assigned to a work which has appeared under varying titles.', 'text', NULL, NOW(), NOW()),
  (12, 'titleStatement', 'Title Statement (245)', 'The title and statement of responsibility area.', 'text', NULL, NOW(), NOW()),
  (12, 'varyingFormTitle', 'Varying Form of Title (246)', 'Portion of the title or an alternative title.', 'text', NULL, NOW(), NOW()),
  (12, 'editionStatement', 'Edition Statement (250)', 'Information relating to the edition of a work.', 'text', NULL, NOW(), NOW()),
  (12, 'publication', 'Publication / Distribution (264)', 'Place, name, and date relating to publication, distribution, manufacture, or copyright.', 'text', NULL, NOW(), NOW()),
  (12, 'physicalDescription', 'Physical Description (300)', 'The physical description of the item (extent, dimensions, accompanying material).', 'text', NULL, NOW(), NOW()),
  (12, 'generalNote', 'General Note (500)', 'General information for which a specific note field has not been defined.', 'textarea', NULL, NOW(), NOW()),
  (12, 'summaryNote', 'Summary (520)', 'Unformatted information about the contents of the item.', 'textarea', NULL, NOW(), NOW()),
  (12, 'subjectTopical', 'Subject — Topical Term (650)', 'A topical term used as a subject added entry.', 'text', NULL, NOW(), NOW()),
  (12, 'subjectGeographic', 'Subject — Geographic Name (651)', 'A geographic name used as a subject added entry.', 'text', NULL, NOW(), NOW()),
  (12, 'addedEntryPersonalName', 'Added Entry — Personal Name (700)', 'A secondary entry under a personal name.', 'text', NULL, NOW(), NOW()),
  (12, 'electronicLocationURL', 'Electronic Location and Access (856)', 'Information needed to locate and access an electronic resource.', 'uri', NULL, NOW(), NOW()),
  (13, 'titleInfo', 'Title Info', 'A word, phrase, character, or group of characters that constitutes the chief title of a resource.', 'text', NULL, NOW(), NOW()),
  (13, 'name', 'Name', 'The name of a person, organisation, or event associated in some way with the resource.', 'text', NULL, NOW(), NOW()),
  (13, 'typeOfResource', 'Type of Resource', 'A term that specifies the characteristics and general type of content of the resource.', 'text', NULL, NOW(), NOW()),
  (13, 'genre', 'Genre', 'A term or terms that designate a category characterising a particular style, form, or content.', 'text', NULL, NOW(), NOW()),
  (13, 'originInfo', 'Origin Info', 'Information about the origin of the resource: place, publisher, date.', 'text', NULL, NOW(), NOW()),
  (13, 'language', 'Language', 'The language(s) of the content of the resource.', 'text', NULL, NOW(), NOW()),
  (13, 'physicalDescription', 'Physical Description', 'Information about the physical attributes of the resource.', 'text', NULL, NOW(), NOW()),
  (13, 'abstract', 'Abstract', 'A summary of the content of the resource.', 'textarea', NULL, NOW(), NOW()),
  (13, 'tableOfContents', 'Table of Contents', 'A description of the contents of the resource.', 'textarea', NULL, NOW(), NOW()),
  (13, 'targetAudience', 'Target Audience', 'A description of the intellectual level, motivation/interest level, subject interest, or special characteristics of the intended audience.', 'text', NULL, NOW(), NOW()),
  (13, 'note', 'Note', 'General textual information relating to a resource.', 'textarea', NULL, NOW(), NOW()),
  (13, 'subject', 'Subject', 'A term or phrase representing the primary topic(s) on which a work is focused.', 'text', NULL, NOW(), NOW()),
  (13, 'classification', 'Classification', 'A designation applied to a resource that indicates the subject by applying a formal system of coding and organising resources.', 'text', NULL, NOW(), NOW()),
  (13, 'relatedItem', 'Related Item', 'Information about other resources related to the resource being described.', 'text', NULL, NOW(), NOW()),
  (13, 'identifier', 'Identifier', 'Contains a unique standard number or code that distinctively identifies a resource.', 'text', NULL, NOW(), NOW()),
  (13, 'location', 'Location', 'Identifies the institution or repository holding the resource, or a remote location in the form of a URL.', 'text', NULL, NOW(), NOW()),
  (13, 'accessCondition', 'Access Condition', 'Information about restrictions imposed on access to a resource.', 'textarea', NULL, NOW(), NOW()),
  (13, 'part', 'Part', 'Designation of physical pages, volumes, tracks of music, frames of film, etc.', 'text', NULL, NOW(), NOW()),
  (13, 'recordInfo', 'Record Info', 'Information about the metadata record.', 'text', NULL, NOW(), NOW()),
  (14, 'title', 'Title', 'Title information associated with a resource (Work or Instance).', 'text', NULL, NOW(), NOW()),
  (14, 'subject', 'Subject', 'Subject term(s) describing the Work.', 'text', NULL, NOW(), NOW()),
  (14, 'contribution', 'Contribution', 'Agent and role associated with the creation of the Work.', 'text', NULL, NOW(), NOW()),
  (14, 'language', 'Language', 'Language associated with a resource.', 'text', NULL, NOW(), NOW()),
  (14, 'content', 'Content Type', 'Content type of the Work (RDA Content Type term).', 'text', NULL, NOW(), NOW()),
  (14, 'summary', 'Summary', 'Summary of the content of the resource.', 'textarea', NULL, NOW(), NOW()),
  (14, 'classification', 'Classification', 'Classification number(s) assigned to the Work.', 'text', NULL, NOW(), NOW()),
  (14, 'intendedAudience', 'Intended Audience', 'Intended audience of the Work.', 'text', NULL, NOW(), NOW()),
  (14, 'genreForm', 'Genre / Form', 'Genre or form of the Work.', 'text', NULL, NOW(), NOW()),
  (14, 'place', 'Place', 'Geographic place associated with the Work.', 'text', NULL, NOW(), NOW()),
  (14, 'identifiedBy', 'Identified By', 'Identifier for the Instance (ISBN, ISSN, etc.).', 'text', NULL, NOW(), NOW()),
  (14, 'publicationStatement', 'Publication Statement', 'Publication statement of the Instance.', 'text', NULL, NOW(), NOW()),
  (14, 'editionStatement', 'Edition Statement', 'Edition statement of the Instance.', 'text', NULL, NOW(), NOW()),
  (14, 'responsibilityStatement', 'Responsibility Statement', 'Statement of responsibility of the Instance.', 'text', NULL, NOW(), NOW()),
  (14, 'media', 'Media Type', 'RDA Media Type of the Instance.', 'text', NULL, NOW(), NOW()),
  (14, 'carrier', 'Carrier Type', 'RDA Carrier Type of the Instance.', 'text', NULL, NOW(), NOW()),
  (14, 'extent', 'Extent', 'Number and type of units of the Instance.', 'text', NULL, NOW(), NOW()),
  (15, 'metsHdr', 'METS Header', 'Header element containing metadata describing the METS document itself.', 'text', NULL, NOW(), NOW()),
  (15, 'dmdSec', 'Descriptive Metadata Section', 'One or more sections of descriptive metadata (e.g., DC, MODS).', 'textarea', NULL, NOW(), NOW()),
  (15, 'amdSec', 'Administrative Metadata Section', 'Technical, rights, source, and digital provenance metadata (PREMIS, MIX).', 'textarea', NULL, NOW(), NOW()),
  (15, 'fileSec', 'File Section', 'Inventory of files comprising the digital object.', 'text', NULL, NOW(), NOW()),
  (15, 'structMap', 'Structural Map', 'Outlines the hierarchical logical or physical structure of the digital object.', 'textarea', NULL, NOW(), NOW()),
  (15, 'structLink', 'Structural Links', 'Hyperlinks between structural map nodes.', 'text', NULL, NOW(), NOW()),
  (15, 'behaviorSec', 'Behavior Section', 'Executable behaviors that can be applied to the digital object.', 'text', NULL, NOW(), NOW()),
  (16, 'productIdentifier', 'Product Identifier', 'An identifier for the product, typically ISBN-13.', 'text', NULL, NOW(), NOW()),
  (16, 'titleDetail', 'Title Detail', 'The title of the product in a specific title type.', 'text', NULL, NOW(), NOW()),
  (16, 'contributor', 'Contributor', 'A contributor to the content of the product (author, editor, illustrator, etc.) with their role.', 'text', NULL, NOW(), NOW()),
  (16, 'language', 'Language', 'Language of the text of the product.', 'text', NULL, NOW(), NOW()),
  (16, 'subject', 'Subject', 'Subject classification (BISAC, BIC, Thema, etc.).', 'text', NULL, NOW(), NOW()),
  (16, 'extent', 'Extent', 'The number of pages, number of words, or duration of the product.', 'text', NULL, NOW(), NOW()),
  (16, 'editionStatement', 'Edition Statement', 'A short free-text description of the edition.', 'text', NULL, NOW(), NOW()),
  (16, 'publisher', 'Publisher', 'The name of the publisher.', 'text', NULL, NOW(), NOW()),
  (16, 'publishingDate', 'Publishing Date', 'Publication date of the product.', 'date', NULL, NOW(), NOW()),
  (16, 'relatedMaterial', 'Related Material', 'Related products or related works.', 'text', NULL, NOW(), NOW()),
  (16, 'textContent', 'Text Content', 'A free text excerpt from the work (blurb, review quote, table of contents).', 'textarea', NULL, NOW(), NOW()),
  (16, 'price', 'Price', 'The price of the product for a specific market and currency.', 'text', NULL, NOW(), NOW()),
  (17, 'referenceCode', 'Reference Code', 'Unique identifier for the unit of description within the repository.', 'text', NULL, NOW(), NOW()),
  (17, 'title', 'Title', 'Name of the unit of description.', 'text', NULL, NOW(), NOW()),
  (17, 'dates', 'Dates', 'Date(s) of creation of the records.', 'date', NULL, NOW(), NOW()),
  (17, 'levelOfDescription', 'Level of Description', 'Level of arrangement of the unit of description (fonds, series, file, item).', 'text', NULL, NOW(), NOW()),
  (17, 'extentAndMedium', 'Extent and Medium', 'Physical extent and medium of the unit of description.', 'text', NULL, NOW(), NOW()),
  (17, 'nameOfCreator', 'Name of Creator', 'Name of the organisation(s) or individual(s) responsible for the creation of the archival unit.', 'text', NULL, NOW(), NOW()),
  (17, 'administrativeHistory', 'Administrative / Biographical History', 'Concise information on the administrative history of the creating body or the life of the creator.', 'textarea', NULL, NOW(), NOW()),
  (17, 'archivalHistory', 'Archival History', 'Successive transfers of ownership, responsibility or custody of the unit of description.', 'textarea', NULL, NOW(), NOW()),
  (17, 'immediateSourceOfAcquisition', 'Immediate Source of Acquisition', 'Source from which the repository directly acquired the unit of description and the date and method of acquisition.', 'textarea', NULL, NOW(), NOW()),
  (17, 'scopeAndContent', 'Scope and Content', 'Enables users to judge the potential relevance of the unit of description.', 'textarea', NULL, NOW(), NOW()),
  (17, 'appraisalDestructionScheduling', 'Appraisal, Destruction and Scheduling', 'Information on any appraisal, destruction and scheduling action.', 'textarea', NULL, NOW(), NOW()),
  (17, 'accruals', 'Accruals', 'Planned additions to the unit of description.', 'textarea', NULL, NOW(), NOW()),
  (17, 'systemOfArrangement', 'System of Arrangement', 'Information about the internal structure, order, and/or classification system of the unit of description.', 'textarea', NULL, NOW(), NOW()),
  (17, 'conditionsGoverningAccess', 'Conditions Governing Access', 'Information on the legal status or other regulations that restrict or affect access to the unit of description.', 'textarea', NULL, NOW(), NOW()),
  (17, 'conditionsGoverningReproduction', 'Conditions Governing Reproduction', 'Restrictions on reproduction of the unit of description after access has been provided.', 'textarea', NULL, NOW(), NOW()),
  (17, 'languageScriptsOfMaterial', 'Language / Scripts of Material', 'Language(s) and/or script(s) of the materials in the unit of description.', 'text', NULL, NOW(), NOW()),
  (17, 'physicalTechnicalRequirements', 'Physical Characteristics and Technical Requirements', 'Physical condition and any technical requirements that affect use of the unit of description.', 'textarea', NULL, NOW(), NOW()),
  (17, 'findingAids', 'Finding Aids', 'Information about any finding aids that relate to the context or content of the unit of description.', 'textarea', NULL, NOW(), NOW()),
  (17, 'existenceAndLocationOfOriginals', 'Existence and Location of Originals', 'Information about the existence, location, availability and/or destruction of originals.', 'textarea', NULL, NOW(), NOW()),
  (17, 'existenceAndLocationOfCopies', 'Existence and Location of Copies', 'Information about copies of the unit of description.', 'textarea', NULL, NOW(), NOW()),
  (17, 'relatedUnitsOfDescription', 'Related Units of Description', 'Information about units of description in the same or other repositories that are related by provenance or other association.', 'textarea', NULL, NOW(), NOW()),
  (17, 'publicationNote', 'Publication Note', 'A citation to, and/or information about a publication based on, using, about or transcribing the unit of description.', 'textarea', NULL, NOW(), NOW()),
  (17, 'note', 'Note', 'Specialised information not accommodated by any of the other areas.', 'textarea', NULL, NOW(), NOW()),
  (17, 'archivistNote', 'Archivist''s Note', 'A note on how the description was prepared and by whom.', 'textarea', NULL, NOW(), NOW()),
  (17, 'rulesOrConventions', 'Rules or Conventions', 'The rules or conventions applied in preparing the description.', 'text', NULL, NOW(), NOW()),
  (17, 'dateOfDescriptions', 'Date(s) of Descriptions', 'Date(s) the entry was prepared and/or revised.', 'date', NULL, NOW(), NOW()),
  (18, 'recordId', 'Record ID', 'A unique persistent identifier for the EAD instance.', 'text', NULL, NOW(), NOW()),
  (18, 'unittitle', 'Unit Title', 'Name of the described materials.', 'text', NULL, NOW(), NOW()),
  (18, 'unitid', 'Unit ID', 'Identifier for the unit of description, typically a reference code.', 'text', NULL, NOW(), NOW()),
  (18, 'unitdatestructured', 'Unit Date (Structured)', 'Date(s) of the materials being described, in structured form.', 'date', NULL, NOW(), NOW()),
  (18, 'physdescstructured', 'Physical Description (Structured)', 'Physical extent and form of the materials being described.', 'text', NULL, NOW(), NOW()),
  (18, 'origination', 'Origination', 'The creator(s) of the materials.', 'text', NULL, NOW(), NOW()),
  (18, 'langmaterial', 'Language of Materials', 'Language(s) of the materials described.', 'text', NULL, NOW(), NOW()),
  (18, 'repository', 'Repository', 'The name and address of the institution holding the described materials.', 'text', NULL, NOW(), NOW()),
  (18, 'abstract', 'Abstract', 'A very brief summary of the materials being described.', 'textarea', NULL, NOW(), NOW()),
  (18, 'scopecontent', 'Scope and Content', 'Describes the nature, scope, and informational content of the described materials.', 'textarea', NULL, NOW(), NOW()),
  (18, 'bioghist', 'Biographical / Historical Note', 'A concise essay about the life and activities of the creator(s).', 'textarea', NULL, NOW(), NOW()),
  (18, 'arrangement', 'Arrangement', 'Information about the arrangement of the materials.', 'textarea', NULL, NOW(), NOW()),
  (18, 'accessrestrict', 'Access Restriction', 'Information about conditions that affect the availability of the materials.', 'textarea', NULL, NOW(), NOW()),
  (18, 'userestrict', 'Use Restriction', 'Information about limitations on the use of the materials after access.', 'textarea', NULL, NOW(), NOW()),
  (18, 'controlaccess', 'Controlled Access', 'Controlled access terms: subject headings, geographic names, personal names, etc.', 'text', NULL, NOW(), NOW()),
  (19, 'entityType', 'Entity Type', 'The type of entity being described: person, corporateBody, or family.', 'text', NULL, NOW(), NOW()),
  (19, 'nameEntry', 'Name Entry', 'A name by which the entity is known.', 'text', NULL, NOW(), NOW()),
  (19, 'nameEntryParallel', 'Parallel Name Entry', 'A parallel form of a name entry (e.g., in another language or script).', 'text', NULL, NOW(), NOW()),
  (19, 'authorizedForm', 'Authorized Form', 'The name form that is the authorised access point.', 'text', NULL, NOW(), NOW()),
  (19, 'alternativeForm', 'Alternative Form', 'An alternative form of a name.', 'text', NULL, NOW(), NOW()),
  (19, 'existDates', 'Exist Dates', 'The dates of existence of the entity (birth/death for persons, founding/dissolution for corporate bodies).', 'date', NULL, NOW(), NOW()),
  (19, 'places', 'Places', 'Significant places associated with the entity.', 'text', NULL, NOW(), NOW()),
  (19, 'legalStatuses', 'Legal Statuses', 'Legal status of a corporate body.', 'text', NULL, NOW(), NOW()),
  (19, 'functions', 'Functions', 'Functions, occupations, and activities of the entity.', 'textarea', NULL, NOW(), NOW()),
  (19, 'occupations', 'Occupations', 'Occupations or roles of a person.', 'text', NULL, NOW(), NOW()),
  (19, 'biogHist', 'Biographical / Historical Note', 'A concise biographical or historical note on the entity.', 'textarea', NULL, NOW(), NOW()),
  (19, 'structureOrGenealogy', 'Structure or Genealogy', 'Internal structural information about a corporate body, or genealogical information about a family.', 'textarea', NULL, NOW(), NOW()),
  (19, 'cpfRelation', 'CPF Relation', 'A relationship between the entity and another corporate body, person, or family.', 'text', NULL, NOW(), NOW()),
  (19, 'resourceRelation', 'Resource Relation', 'A relationship between the entity and archival records or other resources.', 'text', NULL, NOW(), NOW()),
  (20, 'hasCreator', 'Has Creator', 'Relates a record or record set to its creator agent.', 'text', NULL, NOW(), NOW()),
  (20, 'hasAccumulationDate', 'Has Accumulation Date', 'Relates a record or record set to its accumulation date(s).', 'date', NULL, NOW(), NOW()),
  (20, 'hasProvenance', 'Has Provenance', 'Relates a record or record set to an agent that had custody or ownership.', 'text', NULL, NOW(), NOW()),
  (20, 'hasContentOfType', 'Has Content of Type', 'Relates a record or record set to a content type.', 'text', NULL, NOW(), NOW()),
  (20, 'isAssociatedWithPlace', 'Is Associated With Place', 'Relates a thing to a place.', 'text', NULL, NOW(), NOW()),
  (20, 'hasLegalStatus', 'Has Legal Status', 'Relates a thing to a legal status.', 'text', NULL, NOW(), NOW()),
  (20, 'isRelatedTo', 'Is Related To', 'A generic relation between two RiC entities.', 'text', NULL, NOW(), NOW()),
  (20, 'hasIdentifier', 'Has Identifier', 'Relates a thing to an identifier.', 'text', NULL, NOW(), NOW()),
  (20, 'hasTitle', 'Has Title', 'The title associated with a record or record set.', 'text', NULL, NOW(), NOW()),
  (20, 'hasLanguage', 'Has Language', 'Language of a record or record set.', 'text', NULL, NOW(), NOW()),
  (20, 'scopeAndContent', 'Scope and Content', 'Broad description of the scope and content of a record or record set.', 'textarea', NULL, NOW(), NOW()),
  (20, 'conditionsOfAccess', 'Conditions of Access', 'Conditions governing access to the records.', 'textarea', NULL, NOW(), NOW()),
  (21, 'objectIdentifier', 'Object Identifier', 'An unambiguous value that refers to the PREMIS object within the local system.', 'text', NULL, NOW(), NOW()),
  (21, 'objectCategory', 'Object Category', 'Categorisation of the object (intellectual entity, representation, file, or bitstream).', 'text', NULL, NOW(), NOW()),
  (21, 'preservationLevel', 'Preservation Level', 'A high-level description of the overall preservation approach for the object.', 'text', NULL, NOW(), NOW()),
  (21, 'significantProperties', 'Significant Properties', 'Characteristics of a digital object that must be maintained over time.', 'textarea', NULL, NOW(), NOW()),
  (21, 'fixity', 'Fixity (Checksum)', 'A checksum or message digest to verify integrity of the file.', 'text', NULL, NOW(), NOW()),
  (21, 'size', 'Size', 'Size of the stored object in bytes.', 'integer', NULL, NOW(), NOW()),
  (21, 'format', 'Format', 'The file format of the object (PRONOM PUID or MIME type).', 'text', NULL, NOW(), NOW()),
  (21, 'creatingApplication', 'Creating Application', 'The application that created the object.', 'text', NULL, NOW(), NOW()),
  (21, 'originalName', 'Original Name', 'Original filename at the time of ingest.', 'text', NULL, NOW(), NOW()),
  (21, 'storage', 'Storage', 'Storage location or medium identifier.', 'text', NULL, NOW(), NOW()),
  (21, 'eventIdentifier', 'Event Identifier', 'An unambiguous value that refers to the PREMIS event.', 'text', NULL, NOW(), NOW()),
  (21, 'eventType', 'Event Type', 'A term that uniquely identifies the type of event (e.g., ingest, validation, fixity check).', 'text', NULL, NOW(), NOW()),
  (21, 'eventDateTime', 'Event Date/Time', 'The single date and time, or the start date and time of a date range, when the event occurred.', 'date', NULL, NOW(), NOW()),
  (21, 'eventOutcome', 'Event Outcome', 'A term indicating the overall result of the event (success, failure, etc.).', 'text', NULL, NOW(), NOW()),
  (21, 'agentType', 'Agent Type', 'The type of agent performing the event (person, organisation, or software).', 'text', NULL, NOW(), NOW()),
  (22, 'typeOfEntity', 'Type of Entity', 'The type of entity (corporate body, person, or family) being described.', 'text', NULL, NOW(), NOW()),
  (22, 'authorizedFormOfName', 'Authorized Form of Name', 'The standardised form of name for the entity.', 'text', NULL, NOW(), NOW()),
  (22, 'parallelFormsOfName', 'Parallel Forms of Name', 'Forms of the authorised name in different languages or scripts.', 'text', NULL, NOW(), NOW()),
  (22, 'standardizedFormsOfName', 'Standardized Forms of Name', 'Standardised forms of name for the entity constructed according to other conventions.', 'text', NULL, NOW(), NOW()),
  (22, 'datesOfExistence', 'Dates of Existence', 'Dates of existence of the corporate body, person, or family.', 'date', NULL, NOW(), NOW()),
  (22, 'history', 'History', 'A concise history of the corporate body, person, or family.', 'textarea', NULL, NOW(), NOW()),
  (22, 'places', 'Places', 'Significant places associated with the entity.', 'text', NULL, NOW(), NOW()),
  (22, 'legalStatus', 'Legal Status', 'Legal status of a corporate body.', 'text', NULL, NOW(), NOW()),
  (22, 'functions', 'Functions', 'Functions, occupations and activities of the entity.', 'textarea', NULL, NOW(), NOW()),
  (22, 'mandatesOrSources', 'Mandates / Sources of Authority', 'The legal and other mandate(s) under which the corporate body operates.', 'textarea', NULL, NOW(), NOW()),
  (22, 'internalStructure', 'Internal Structure / Genealogy', 'Significant information about the internal structure of a corporate body, or the genealogy of a family.', 'textarea', NULL, NOW(), NOW()),
  (22, 'generalContext', 'General Context', 'Significant general social, cultural, economic, political, and/or historical context.', 'textarea', NULL, NOW(), NOW()),
  (22, 'relatedCorporateBodies', 'Related Corporate Bodies / Persons / Families', 'The name of the related corporate body, person, or family and the nature of the relationship.', 'text', NULL, NOW(), NOW()),
  (23, 'E1_CRM_Entity', 'E1 CRM Entity', 'The most general class of the CIDOC CRM. All classes are subclasses of this.', 'text', NULL, NOW(), NOW()),
  (23, 'E18_Physical_Thing', 'E18 Physical Thing', 'Subclass of E1 CRM Entity — a thing with a physical form.', 'text', NULL, NOW(), NOW()),
  (23, 'E22_Human_Made_Object', 'E22 Human-Made Object', 'A physical object purposely created by human activity.', 'text', NULL, NOW(), NOW()),
  (23, 'E21_Person', 'E21 Person', 'A real person, living or deceased.', 'text', NULL, NOW(), NOW()),
  (23, 'E74_Group', 'E74 Group', 'Any gatherings or organisation of Actors.', 'text', NULL, NOW(), NOW()),
  (23, 'E52_Time_Span', 'E52 Time-Span', 'A period in time.', 'date', NULL, NOW(), NOW()),
  (23, 'E53_Place', 'E53 Place', 'An extent in space.', 'text', NULL, NOW(), NOW()),
  (23, 'E55_Type', 'E55 Type', 'A set of categories or terms forming a classification scheme.', 'text', NULL, NOW(), NOW()),
  (23, 'E65_Creation', 'E65 Creation', 'The event of bringing an item into existence (intellectual/conceptual creation).', 'text', NULL, NOW(), NOW()),
  (23, 'E12_Production', 'E12 Production', 'The event of producing a physical object.', 'text', NULL, NOW(), NOW()),
  (23, 'P1_is_identified_by', 'P1 is identified by', 'Associates an item with an identifier or appellation.', 'text', NULL, NOW(), NOW()),
  (23, 'P2_has_type', 'P2 has type', 'Categorises the subject with the object.', 'text', NULL, NOW(), NOW()),
  (23, 'P4_has_time_span', 'P4 has time-span', 'Defines the time-span of the period or event.', 'date', NULL, NOW(), NOW()),
  (23, 'P7_took_place_at', 'P7 took place at', 'The location at which an event took place.', 'text', NULL, NOW(), NOW()),
  (23, 'P14_carried_out_by', 'P14 carried out by', 'The agent who carried out an activity.', 'text', NULL, NOW(), NOW()),
  (23, 'P43_has_dimension', 'P43 has dimension', 'Dimension(s) of the physical thing (height, width, depth, weight).', 'text', NULL, NOW(), NOW()),
  (23, 'P45_consists_of', 'P45 consists of', 'The material(s) of which the object is composed.', 'text', NULL, NOW(), NOW()),
  (23, 'P52_has_current_owner', 'P52 has current owner', 'The current legal owner of the physical thing.', 'text', NULL, NOW(), NOW()),
  (23, 'P55_has_current_location', 'P55 has current location', 'The current location of the physical thing.', 'text', NULL, NOW(), NOW()),
  (23, 'P62_depicts', 'P62 depicts', 'The entities visually represented in an image.', 'text', NULL, NOW(), NOW()),
  (24, 'objectNumber', 'Object Number', 'Unique accession number or identifier assigned to the object.', 'text', NULL, NOW(), NOW()),
  (24, 'objectName', 'Object Name', 'The name by which the object is known.', 'text', NULL, NOW(), NOW()),
  (24, 'objectDescription', 'Object Description', 'A textual description of the object''s appearance, subject matter, and significant features.', 'textarea', NULL, NOW(), NOW()),
  (24, 'objectProduction', 'Object Production', 'Information about the production of the object: maker, date, place, method.', 'text', NULL, NOW(), NOW()),
  (24, 'objectHistory', 'Object History', 'The known history of the object from creation to acquisition.', 'textarea', NULL, NOW(), NOW()),
  (24, 'objectCondition', 'Object Condition', 'A description of the physical condition of the object.', 'textarea', NULL, NOW(), NOW()),
  (24, 'objectValuation', 'Object Valuation', 'The current assessed value of the object.', 'text', NULL, NOW(), NOW()),
  (24, 'currentLocation', 'Current Location', 'The current physical location of the object within the institution.', 'text', NULL, NOW(), NOW()),
  (24, 'objectEntryDetails', 'Object Entry Details', 'Information about how the object arrived at the institution.', 'textarea', NULL, NOW(), NOW()),
  (24, 'acquisitionDetails', 'Acquisition Details', 'Information about the formal acquisition of the object (method, date, source, cost).', 'textarea', NULL, NOW(), NOW()),
  (24, 'loanInDetails', 'Loan In Details', 'Details of the loan agreement when the object is on loan to the institution.', 'textarea', NULL, NOW(), NOW()),
  (24, 'loanOutDetails', 'Loan Out Details', 'Details of the loan agreement when the object is loaned to another institution.', 'textarea', NULL, NOW(), NOW()),
  (24, 'movementDetails', 'Movement Details', 'A record of each movement of the object within or outside the institution.', 'textarea', NULL, NOW(), NOW()),
  (24, 'ownershipDetails', 'Ownership Details', 'Information about who owns the object.', 'text', NULL, NOW(), NOW()),
  (24, 'rights', 'Rights', 'Copyright and intellectual property rights information.', 'textarea', NULL, NOW(), NOW()),
  (25, 'lidoRecID', 'LIDO Record ID', 'A unique persistent identifier for the LIDO record.', 'text', NULL, NOW(), NOW()),
  (25, 'objectPublishedID', 'Object Published ID', 'A globally unique identifier for the object published on the web.', 'uri', NULL, NOW(), NOW()),
  (25, 'category', 'Category', 'The CIDOC CRM class that is the overall type of the described object.', 'text', NULL, NOW(), NOW()),
  (25, 'objectClassification', 'Object Classification', 'Classification of the object using standardised terminology (object name, classification).', 'text', NULL, NOW(), NOW()),
  (25, 'objectIdentification', 'Object Identification', 'Title, inscriptions, repository, and measurements of the object.', 'text', NULL, NOW(), NOW()),
  (25, 'objectMeasurements', 'Object Measurements', 'The dimensions or other measurements of the object.', 'text', NULL, NOW(), NOW()),
  (25, 'eventWrap', 'Events', 'Events associated with the object (production, acquisition, exhibition, etc.).', 'textarea', NULL, NOW(), NOW()),
  (25, 'eventType', 'Event Type', 'The type of event (e.g., Production, Acquisition, Exhibition, Move, Loss, Restoration, Provenance).', 'text', NULL, NOW(), NOW()),
  (25, 'eventDate', 'Event Date', 'The date(s) of the event.', 'date', NULL, NOW(), NOW()),
  (25, 'eventActor', 'Event Actor', 'An actor (person or organisation) involved in the event.', 'text', NULL, NOW(), NOW()),
  (25, 'objectRelation', 'Object Relation', 'Relationships of the object to other objects or subjects.', 'text', NULL, NOW(), NOW()),
  (25, 'rightsWork', 'Rights of Work', 'Rights information about the object.', 'textarea', NULL, NOW(), NOW()),
  (25, 'recordSource', 'Record Source', 'The institution or person that provided the record.', 'text', NULL, NOW(), NOW()),
  (25, 'resourceSet', 'Resource Set', 'Digital resources representing the object (images, 3D scans, etc.).', 'uri', NULL, NOW(), NOW()),
  (26, 'typeOfObject', 'Type of Object', 'The specific type of object being documented (e.g., painting, sculpture, vase, coin).', 'text', NULL, NOW(), NOW()),
  (26, 'materialsAndTechniques', 'Materials and Techniques', 'The materials from which the object is made and the techniques used to make it.', 'text', NULL, NOW(), NOW()),
  (26, 'measurements', 'Measurements', 'The dimensions and/or weight of the object.', 'text', NULL, NOW(), NOW()),
  (26, 'inscriptionsAndMarkings', 'Inscriptions and Markings', 'Any lettering, inscriptions, labels, stamps, and/or hallmarks on the object.', 'textarea', NULL, NOW(), NOW()),
  (26, 'distinguishingFeatures', 'Distinguishing Features', 'Any unusual features, damage, or repair that may be used to distinguish the object.', 'textarea', NULL, NOW(), NOW()),
  (26, 'titleOrSubject', 'Title or Subject', 'The title by which the object is known, or a brief description of its subject.', 'text', NULL, NOW(), NOW()),
  (26, 'datePeriod', 'Date or Period', 'The date or period of production of the object.', 'date', NULL, NOW(), NOW()),
  (26, 'maker', 'Maker', 'The person(s) or organisation(s) responsible for making the object.', 'text', NULL, NOW(), NOW()),
  (26, 'images', 'Images', 'Photographic images of the object from multiple angles.', 'uri', NULL, NOW(), NOW()),
  (27, 'type', 'EDM Type', 'The type of the provided object (TEXT, IMAGE, SOUND, VIDEO, 3D).', 'text', NULL, NOW(), NOW()),
  (27, 'rights', 'Rights', 'The rights statement for the object (Creative Commons URI or RightsStatements.org URI).', 'uri', NULL, NOW(), NOW()),
  (27, 'dataProvider', 'Data Provider', 'The name of the organisation that provides data to an aggregator.', 'text', NULL, NOW(), NOW()),
  (27, 'provider', 'Provider', 'The name of the aggregating organisation that provided data to Europeana.', 'text', NULL, NOW(), NOW()),
  (27, 'isShownAt', 'Is Shown At', 'An unambiguous URL reference to the digital object on the provider''s website.', 'uri', NULL, NOW(), NOW()),
  (27, 'isShownBy', 'Is Shown By', 'An unambiguous URL reference to a digital representation of the CHO.', 'uri', NULL, NOW(), NOW()),
  (27, 'object', 'Object', 'The URL of a thumbnail representing the digital object.', 'uri', NULL, NOW(), NOW()),
  (27, 'currentLocation', 'Current Location', 'The geographic location and/or name of the repository where the physical object resides.', 'text', NULL, NOW(), NOW()),
  (27, 'hasMet', 'Has Met', 'A reference to entities or events the described object has been associated with.', 'text', NULL, NOW(), NOW()),
  (27, 'hasType', 'Has Type', 'A type of the described resource beyond the EDM type.', 'text', NULL, NOW(), NOW()),
  (27, 'incorporates', 'Incorporates', 'A work that is incorporated in the described work.', 'text', NULL, NOW(), NOW()),
  (27, 'realizationOf', 'Realisation Of', 'Relates an instance to the work of which it is a realisation.', 'uri', NULL, NOW(), NOW()),
  (27, 'isDerivativeOf', 'Is Derivative Of', 'An original work from which the described object is derived.', 'uri', NULL, NOW(), NOW()),
  (27, 'wasPresentAt', 'Was Present At', 'An event at which the described object was present.', 'text', NULL, NOW(), NOW()),
  (28, 'prefLabel', 'Preferred Label', 'The preferred lexical label for a resource, in a given language.', 'text', NULL, NOW(), NOW()),
  (28, 'altLabel', 'Alternative Label', 'An alternative lexical label for a resource (variant, abbreviation, synonym).', 'text', NULL, NOW(), NOW()),
  (28, 'hiddenLabel', 'Hidden Label', 'A lexical label for a resource that should be hidden when generating visual displays.', 'text', NULL, NOW(), NOW()),
  (28, 'definition', 'Definition', 'A statement or formal explanation of the meaning of a concept.', 'textarea', NULL, NOW(), NOW()),
  (28, 'scopeNote', 'Scope Note', 'A note that helps clarify the meaning and/or the use of a concept.', 'textarea', NULL, NOW(), NOW()),
  (28, 'example', 'Example', 'An example of the use of a concept.', 'textarea', NULL, NOW(), NOW()),
  (28, 'historyNote', 'History Note', 'A note about the past status/use/meaning of a concept.', 'textarea', NULL, NOW(), NOW()),
  (28, 'editorialNote', 'Editorial Note', 'A note for an editor, translator, or maintainer of the vocabulary.', 'textarea', NULL, NOW(), NOW()),
  (28, 'notation', 'Notation', 'A notation, code, or classification number (e.g., Dewey number, AAT ID).', 'text', NULL, NOW(), NOW()),
  (28, 'broader', 'Broader', 'Relates a concept to a concept that is more general in meaning.', 'text', NULL, NOW(), NOW()),
  (28, 'narrower', 'Narrower', 'Relates a concept to a concept that is more specific in meaning.', 'text', NULL, NOW(), NOW()),
  (28, 'related', 'Related', 'Relates a concept to a concept with which there is an associative semantic relationship.', 'text', NULL, NOW(), NOW()),
  (28, 'inScheme', 'In Scheme', 'Relates a resource to the concept scheme of which it is part.', 'uri', NULL, NOW(), NOW()),
  (28, 'hasTopConcept', 'Has Top Concept', 'Relates a concept scheme to a concept which is topmost in the broader/narrower concept hierarchy.', 'text', NULL, NOW(), NOW()),
  (29, 'id', 'ID', 'The URI that identifies the IIIF resource.', 'uri', NULL, NOW(), NOW()),
  (29, 'type', 'Type', 'The type of IIIF resource (Manifest, Collection, Canvas, AnnotationPage, etc.).', 'text', NULL, NOW(), NOW()),
  (29, 'label', 'Label', 'A human-readable label for the resource, intended for display to the user.', 'text', NULL, NOW(), NOW()),
  (29, 'summary', 'Summary', 'A short textual summary intended to be conveyed to the user when the metadata property is not shown.', 'textarea', NULL, NOW(), NOW()),
  (29, 'metadata', 'Metadata', 'An ordered list of label/value pairs for display to the user.', 'textarea', NULL, NOW(), NOW()),
  (29, 'requiredStatement', 'Required Statement', 'A required statement of attribution or other information that must be shown to the user.', 'text', NULL, NOW(), NOW()),
  (29, 'rights', 'Rights', 'A string that identifies a license or rights statement that applies to the content.', 'uri', NULL, NOW(), NOW()),
  (29, 'logo', 'Logo', 'A small image that represents an agent (organisation or person).', 'uri', NULL, NOW(), NOW()),
  (29, 'thumbnail', 'Thumbnail', 'A content resource intended to be used as a thumbnail for the resource.', 'uri', NULL, NOW(), NOW()),
  (29, 'homepage', 'Homepage', 'A web page that is about the object represented by the resource.', 'uri', NULL, NOW(), NOW()),
  (29, 'seeAlso', 'See Also', 'A machine-readable resource (e.g., MODS/RDF) that is related to the current resource.', 'uri', NULL, NOW(), NOW()),
  (29, 'partOf', 'Part Of', 'A containing resource that includes the current resource.', 'uri', NULL, NOW(), NOW()),
  (29, 'start', 'Start Canvas', 'A Canvas, or part of a Canvas, that the client should display on initialisation.', 'uri', NULL, NOW(), NOW()),
  (29, 'viewingDirection', 'Viewing Direction', 'The direction in which Canvases should be presented (left-to-right, right-to-left, top-to-bottom, bottom-to-top).', 'text', NULL, NOW(), NOW());

-- ═══ Done. Verify with:
-- SELECT v.id, v.prefix, v.label, count(p.id) AS properties
-- FROM metadata_vocabularies v
-- LEFT JOIN metadata_properties p ON p.vocabulary_id = v.id
-- WHERE v.id >= 6
-- GROUP BY v.id, v.prefix, v.label
-- ORDER BY v.id;
