apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voile-ingress
  namespace: voile
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: voile.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voile
                port:
                  number: 80
