import Config

# Configure your database
config :voile, Voile.Repo,
  username: System.get_env("VOILE_POSTGRES_USER") || "postgres",
  password: System.get_env("VOILE_POSTGRES_PASSWORD") || "postgres",
  hostname: System.get_env("VOILE_POSTGRES_HOSTNAME") || "localhost",
  database: System.get_env("VOILE_POSTGRES_DB") || "voile_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  # Set timezone to Indonesia (GMT+7)
  parameters: [timezone: "Asia/Jakarta"],
  # Optimize for migration workloads
  queue_target: 50,
  queue_interval: 1000,
  # Reduce idle timeout to prevent long idle connections
  pool_timeout: 15000,
  # Increase checkout timeout for large batch operations
  timeout: 60000

# Configure MySQL/MariaDB source for SLiMS data migration
# Works with both MySQL and MariaDB databases using the same configuration
# Uncomment and configure to use database connection instead of CSV files
config :voile, :mysql_source,
  hostname: "localhost",
  # Default port for MySQL/MariaDB
  port: 3306,
  # Database username
  username: "root",
  # Database password
  password: "",
  # SLiMS database name
  database: "slims_gold"

# Configure OAuth with Assent
config :assent,
  google: [
    client_id: System.get_env("VOILE_GOOGLE_CLIENT_ID"),
    client_secret: System.get_env("VOILE_GOOGLE_CLIENT_SECRET"),
    redirect_uri: System.get_env("VOILE_GOOGLE_REDIRECT_URI")
  ]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Binding to loopback ipv4 address prevents access from other machines.
config :voile, VoileWeb.Endpoint,
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [
    ip: {0, 0, 0, 0},
    port: String.to_integer(System.get_env("PORT") || "4000")
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "8yUfAjPlnRwlXp8kQaME2eoN8nXCApsGmofKKaAMoeKsThy5ZHE2XTKdE1fKjH9c",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:voile, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:voile, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :voile, VoileWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/voile_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :voile, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

config :swoosh, :api_client, false

# Use Gmail API adapter in development if requested
if System.get_env("VOILE_MAILER_ADAPTER") == "gmail_api" do
  config :voile, Voile.Mailer,
    adapter: Voile.Mailer.GmailApiAdapter,
    access_token: System.get_env("VOILE_GMAIL_ACCESS_TOKEN"),
    refresh_token: System.get_env("VOILE_GMAIL_REFRESH_TOKEN"),
    client_id: System.get_env("VOILE_GMAIL_CLIENT_ID"),
    client_secret: System.get_env("VOILE_GMAIL_CLIENT_SECRET"),
    redirect_uri: System.get_env("VOILE_GMAIL_REDIRECT_URI")
end

# Disable email queue in development (prevents background email processing)
config :voile, :disable_email_queue, false

# Xendit Payment Gateway Configuration (Development)
# Get your API keys from https://dashboard.xendit.co/settings/developers#api-keys
# For development, you can hardcode test keys here or use environment variables
config :voile,
  xendit_api_key:
    System.get_env("VOILE_XENDIT_API_KEY") || "xnd_development_REPLACE_WITH_YOUR_KEY",
  xendit_webhook_token: System.get_env("VOILE_XENDIT_WEBHOOK_TOKEN") || "REPLACE_WITH_YOUR_TOKEN"

# OAI-PMH Configuration (Development)
config :voile,
  oai_pmh_repository_id: "localhost:4000"
