import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :voile, VoileWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Force HTTPS in production: redirect any plain-HTTP request to HTTPS and
  # send HSTS headers so browsers pin to TLS. `rewrite_on` trusts the
  # X-Forwarded-Proto header set by the reverse proxy / load balancer.
  #
  # NOTE: force_ssl is a compile-time option for the Endpoint.
  #
  # To TEST with runtime config (without recompiling):
  #   1. Remove force_ssl from this file (config/prod.exs)
  #   2. Add it to config/runtime.exs in the Endpoint config block
  #   3. Rebuild and deploy
  #   4. If it works, move it back here for production
  #
  # For production with proper compile-time config:
  force_ssl: [hsts: true, rewrite_on: [:x_forwarded_proto]]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Voile.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Structured JSON logging for production (OpenObserve / Google Cloud compatible)
config :logger, :default_handler, formatter: {LoggerJSON.Formatters.GoogleCloud, metadata: :all}

# Ensure email queue is enabled for production (do not use local mailbox)
config :voile, disable_email_queue: false

# Gmail SMTP setup instructions:
# To use Gmail SMTP, set these environment variables in your production environment:
# VOILE_MAILER_ADAPTER=smtp
# VOILE_SMTP_RELAY=smtp.gmail.com
# VOILE_SMTP_PORT=587
# VOILE_SMTP_USERNAME=your_gmail_address@gmail.com
# VOILE_SMTP_PASSWORD=your_gmail_app_password
# VOILE_SMTP_SSL=false
#
# You must use an App Password for Gmail (not your regular password).
# See: https://support.google.com/accounts/answer/185833

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
