defmodule VoileWeb.ErrorHTML do
  @moduledoc """
  This module is invoked by your endpoint in case of errors on HTML requests.

  See config/config.exs.
  """
  use VoileWeb, :html

  # Enrich assigns with defaults before passing to templates.
  # These render/2 clauses are defined BEFORE embed_templates so they take
  # precedence over the generated clauses (Elixir matches in definition order).
  for template <- ["404.html", "500.html", "503.html"] do
    def render(unquote(template), assigns) do
      enriched = enrich_assigns(unquote(template), assigns)
      # Call the inner template function generated by embed_templates.
      # embed_templates names the function after the template atom, e.g. :"404.html"
      apply(__MODULE__, String.to_atom(unquote(template)), [enriched])
    end
  end

  embed_templates "error_html/*"

  # Fallback for any template without an explicit file (returns plain text).
  def render(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end

  defp enrich_assigns(template, assigns) do
    assigns
    |> Enum.into(%{})
    |> Map.put_new(:current_scope, nil)
    |> Map.put_new(:current_user, nil)
    |> Map.put_new(:flash, %{})
    |> Map.put_new(:app_main_color, "#9333ea")
    |> Map.put_new(:app_secondary_color, "#7c3aed")
    |> Map.put_new(:page_title, get_page_title(template))
    |> Map.put_new(:request_id, get_in(assigns, [:conn, Access.key(:assigns, %{}), :request_id]))
    |> Map.put_new(:status, assigns[:status])
    |> Map.put_new(:requested_url, safe_request_url(assigns[:conn]))
  end

  defp safe_request_url(%Plug.Conn{} = conn), do: Plug.Conn.request_url(conn)
  defp safe_request_url(_), do: "(unknown)"

  defp get_page_title("404.html"), do: "Page Not Found"
  defp get_page_title("500.html"), do: "Internal Server Error"
  defp get_page_title("503.html"), do: "Service Unavailable"
  defp get_page_title(_), do: "Error"
end
